### ISSUE TITLE
epicsCoreJava 7.0.8 update

### ISSUE THREAD

**Issue by tynanford** [ornl-epics/pvws#11]
Just checking in on what is needed to update pvws to include the new epics core release. It seems like core-pv from org.phoebus has to be updated to a new version in the phoebus repository and then the pom.xml updated here?

**Comment by kasemir** [comment]
Yes, right now you'd have to build phoebus' core-pv locally, resulting in  4.6.10-SNAPSHOT, https://github.com/ControlSystemStudio/phoebus/blob/c1f01895c84c92968cc910170bc862870d137eab/core/pv/pom.xml#L7

Then update the PVWS pom from 
https://github.com/ornl-epics/pvws/blob/8074a95a8a25f747fd035b346a43fe5f81c5cf32/pom.xml#L34 to core-pv 4.6.10-SNAPSHOT.

**Comment by tynanford** [comment]
Perfect, thanks!

**Comment by kasemir** [comment]
Let's keep this open since we should in fact update/release phoebus, and then switch pvws to the updated version.
Gives us some 'echo' timeout config param for CA and allows working on "compressed" PVA image data.

**Comment by tynanford** [comment]
That's right. It also gives us the alarm levels for PVs with only a high or
a low value defined which I'm personally looking forward to.

**Comment by kasemir** [comment]
Right.
@shroffk, how about a phoebus release this month?

**Comment by kasemir** [comment]
I've updated PVWS to use core-pv 4.7.0, the latest release.
That results in vtype 1.0.5 and epics-util 1.0.5 , which is the latest and I believe includes the fix for ranges that have NaN on one but not both ends.

**Comment by tynanford** [comment]
Looks good, I can confirm it includes the fix for ranges!
