### ISSUE TITLE
http://localhost:8080/pvws  404NotFound

### ISSUE THREAD

**Issue by zhuzzzzzz** [ornl-epics/pvws#16]
After I deployed the pvws.war package in /webapps/ , it creates a /pvws/ dirctory
But  I still cannot access http://localhost:8080/pvws, it suggests 404NotFound.

I tried to look at the log and found this, so what happened and what should I do?

19-Apr-2023 15:27:34.524 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/zhu/apache-tomcat/webapps/pvws.war]

19-Apr-2023 15:27:35.186 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file

19-Apr-2023 15:27:35.189 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/pvws] startup failed due to previous errors

19-Apr-2023 15:27:35.200 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/zhu/apache-tomcat/webapps/pvws.war] has finished in [675] ms

**Comment by kasemir** [comment]
What's your tomcat version? If it's 10 or higher, see #13

**Comment by zhuzzzzzz** [comment]
it is 8.5.87

**Comment by zhuzzzzzz** [comment]
It works, Thanks very much
I think it is just the matter of  jdk version. I can not successfully bulid the project or run the  binary file in tomcat under jdk11 but in jdk17 both of them works.
