### ISSUE TITLE
Cannot get ByteArrays as an array of ints

### ISSUE THREAD

**Issue by rjwills28** [ornl-epics/pvws#20]
We have been testing pvws/dbwr with an EPICS waveform PV of type CHAR/UCHAR, e.g.
```
record (waveform, "test:message")
{
    field (NELM, "100")
    field (FTVL, "CHAR")
}
```
In **Phoebus** we can display this PV as a string or as an array of integers, i.e.:
![phoebus_char_waveform](https://github.com/ornl-epics/pvws/assets/45264327/29aaf896-8d9b-4e36-9722-f36150182359)

However when we display the same BOB file in **dbwr** we notice different behaviour and cannot display it as an array of ints:
![dbwr_char_waveform](https://github.com/ornl-epics/pvws/assets/45264327/e65faf58-c8b8-469c-aded-038346d438c6)

I took a look at the pvws response and see that no information on the underlying array is sent back - only the converted string is sent. 

I forked and created a branch with a potential fix for this, which is basically to also handle ByteBuffer types as integers as well as a string. See https://github.com/ornl-epics/pvws/compare/main...rjwills28:pvws:char_waveform_fix. I can create a PR if this is agreed as a suitable solution?

**Comment by kasemir** [comment]
OK. Does this only require a change to the PVWS, or do you also need to update the 'format' handling in the DBWR?

**Comment by rjwills28** [comment]
When the format for the widget is set to `decimal` in Phoebus, then DBWR will already display the PV correctly as an array of ints. However there is a slight difference in behaviour between Phoebus and DBWR when the format is left as `default`; Phoebus displays it as an array while DBWR displays it as a string. See example below where I have tested with my proposed fix and note the `format: default` case.

**Phoebus**:
![phoebus_char_waveform_default](https://github.com/ornl-epics/pvws/assets/45264327/042d321a-8796-46bf-a460-212b2c817e67)
**DBWR**:
![dbwr_char_waveform_default png](https://github.com/ornl-epics/pvws/assets/45264327/ba6c1f44-968a-4172-b98c-b24bed84d0df)

If DBWR should follow the behaviour of Phoebus then I think a change is also required in DBWR? I can create an issue on the DBWR repo.

**Comment by kasemir** [comment]
See #21: All byte arrays are sent as strings. On the client end (DBWR) we thus no longer know if the data was really a string, or a char array used to avoid string length limitations.
Fix would be to add a new  "b64byt" data type that sends byte arrays as, well, byte arrays. The client can then by default show them as such, or format as string when the format option is set as such.

**Comment by kasemir** [comment]
Maybe start by handling #21, add "b64flt", "b64srt" and then "b64byt" for this.

**Comment by kasemir** [comment]
By adding `b64byt` to PVWS and then handling fomat='string' in DBWB, this should be fixed.
Thanks!
