### ISSUE TITLE
pvws in docker - update core-pv

### ISSUE THREAD

**Issue by GDH-ISIS** [ornl-epics/pvws#22]
Would it be possible to update core-pv in pom.xml from 4.7.0 to 4.7.3 please?

We are using Docker to run numerous phoebus services, but have come across some IPV6 issues with docker. This has been resolved and requires core-pv version 4.7.3. By manually implementing this change for pvws, we are able to use dbwr to view phoebus screens with live PV values, as well as connect other languages to pvws for json info of PVs (we use pvaccess).

Note :
Environment variable for docker usage.
EPICS_PVA_ENABLE_IPV6='NO'

**Comment by kasemir** [comment]
Sure, create a PR since it looks like you already did and tested that locally

**Comment by GDH-ISIS** [comment]
All complete and working. Many thanks.
