### ISSUE TITLE
"readonly" field never show up or alwalys show up in WebSocket response

### ISSUE THREAD

**Issue by wanglin86769** [ornl-epics/pvws#27]
It seems that the "readonly" field is intended to show up when it changes, but I came across two problems with regard to this field,
1. The data types for last_readonly and readonly are primitive boolean, so if the PV readonly status equals to the initial value, it never show up in WebSocket response.
2. last_readonly is pv.isReadonly() whereas readonly is pv.isReadonly() || !PV_WRITE_SUPPORT, which means they are not consistent. If pv.isReadonly() is false and PV_WRITE_SUPPORT is false, last_readonly does not equal to readonly all the time and the "readonly" field always show up in WebSocket response.

Probably PR #26  is one solution, but not sure whether the Boolean class will affect the performance.

**Comment by kasemir** [comment]
Fixed with #26
