### ISSUE TITLE
Sending alarm levels

### ISSUE THREAD

**Issue by tynanford** [ornl-epics/pvws#8]
Hi Kay, what do you think of having the HIHI, HIGH, LOW, and LOLO values sent on subscribing to a PV, similar to the other meta data?

**Comment by kasemir** [comment]
Yes, I can look at that. I would not create a separate subscription to say"XX.HIHI", "XX.HIGH" etc. but instead send the "display" information that's already available in the metadata, but I think that's what you had in mind as well.

**Comment by tynanford** [comment]
Great, thank you. That is exactly right
